  services:
    - type: web
      name: lab-chatbot-backend
      runtime: python
      runtimeVersion: 3.13.9
      plan: free
      buildCommand: pip install -r requirements.txt
      startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
      envVars:
        - key: DB_HOST
          value: ${DB_HOST}
        - key: DB_PORT
          value: 5432
        - key: DB_NAME
          value: analyticaldata
        - key: DB_USER
          value: postgres
        - key: DB_PASSWORD
          fromFile: .env
        - key: OPENAI_API_KEY
          fromFile: .env
        - key: LLM_MODEL
          value: gpt-4o-mini